/*
 *  stdp_structpl_module.cpp
 *
 *  This file is part of STDPStructplast.
 *
 *  Copyright (C) 2017, see AUTHORS.
 *
 *  STDPStructplast is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  STDPStructplast is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with STDPStructplast.  If not, see <http://www.gnu.org/licenses/>.
 *
 * For more information see: https://github.com/flinz/nest-module-STDPStructplast
 */

#include "stdp_structpl_module.h"

// Generated includes:
#include "config.h"

// include headers with your own stuff
#include "stdp_structpl_connection_hom.h"

// Includes from nestkernel:
#include "connection_manager_impl.h"
#include "connector_model_impl.h"
#include "dynamicloader.h"
#include "exceptions.h"
#include "kernel_manager.h"
#include "model.h"
#include "model_manager_impl.h"
#include "nestmodule.h"
#include "target_identifier.h"

// Includes from sli:
#include "booldatum.h"
#include "integerdatum.h"
#include "sliexceptions.h"
#include "tokenarray.h"

// -- Interface to dynamic module loader ---------------------------------------

/*
 * There are three scenarios, in which STDPStructplastModule can be loaded by NEST:
 *
 * 1) When loading your module with `Install`, the dynamic module loader must
 * be able to find your module. You make the module known to the loader by
 * defining an instance of your module class in global scope. (LTX_MODULE is
 * defined) This instance must have the name
 *
 * <modulename>_LTX_mod
 *
 * The dynamicloader can then load modulename and search for symbol "mod" in it.
 *
 * 2) When you link the library dynamically with NEST during compilation, a new
 * object has to be created. In the constructor the DynamicLoaderModule will
 * register your module. (LINKED_MODULE is defined)
 *
 * 3) When you link the library statically with NEST during compilation, the
 * registration will take place in the file `static_modules.h`, which is
 * generated by cmake.
 */
#if defined( LTX_MODULE ) | defined( LINKED_MODULE )
stdpstructpl::STDPStructplastModule STDPStructplastModule_LTX_mod;
#endif
// -- DynModule functions ------------------------------------------------------

stdpstructpl::STDPStructplastModule::STDPStructplastModule()
{
#ifdef LINKED_MODULE
  // register this module at the dynamic loader
  // this is needed to allow for linking in this module at compile time
  // all registered modules will be initialized by the main app's dynamic loader
  nest::DynamicLoaderModule::registerLinkedModule( this );
#endif
}

stdpstructpl::STDPStructplastModule::~STDPStructplastModule()
{
}

const std::string
stdpstructpl::STDPStructplastModule::name( void ) const
{
  return std::string( "Combined STDP and Structplast Connection" ); // Return name of the module
}

const std::string
stdpstructpl::STDPStructplastModule::commandstring( void ) const
{
  // Instruct the interpreter to load STDPStructplastModule-init.sli
  return std::string( "(stdp_structpl_module-init) run" );
}

//-------------------------------------------------------------------------------------

void
stdpstructpl::STDPStructplastModule::init( SLIInterpreter* i )
{

  nest::kernel()
    .model_manager.register_connection_model< STDPStructplConnectionHom< nest::TargetIdentifierPtrRport > >(
      "stdp_structpl_synapse_hom" );

  nest::kernel()
    .model_manager.register_connection_model< STDPStructplConnectionHom< nest::TargetIdentifierIndex > >(
      "stdp_structpl_synapse_hom_hpc" );


} // STDPStructplastModule::init()
